### ISSUE TITLE
Uncaught SyntaxError: ~/.software/data.json: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Laomoalosi** [swdotcom/swdc-atom#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Linux Mint
**Thrown From**: [code-time](https://github.com/swdotcom/swdc-atom) package 4.1.15

### Stack Trace

Uncaught SyntaxError: /home/laone/.software/data.json: Unexpected token u in JSON at position 0

```
At /home/laone/.atom/packages/code-time/node_modules/file-it/dist/managers/file.js:379

SyntaxError: /home/laone/.software/data.json: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/code-time/node_modules/file-it/dist/managers/file.js:370:37
    at Array.map (<anonymous>)
    at /packages/code-time/node_modules/file-it/dist/managers/file.js:368:22)
    at Object.dashboardMgr.sendOfflineData (/packages/music-time/lib/DashboardManager.js:30:33)
    at /packages/music-time/lib/Activator.js:171:26
```

### Commands

```
     -8:16.8.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -8:08.9.0 Code-Time:open-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -7:56.2.0 Code-Time:web-dashboard (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
  9x -7:44.5.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -3:27.1.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
  3x -3:17.8.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -2:08.4.0 Music-Time:musictime-learn-more (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -2:03.6.0 Music-Time:refresh-treeview (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -1:47.8.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
  3x -1:28.1.0 core:backspace (input.hidden-input)
  2x -1:27.4.0 core:move-right (input.hidden-input)
  6x -1:26.9.0 core:backspace (input.hidden-input)
     -1:21.6.0 core:move-left (input.hidden-input)
  9x -1:21 core:move-right (input.hidden-input)
  3x -1:17.8.0 Code-Time:refresh-code-time-metrics (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:12.3.0 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```
autocomplete-sql 0.5.0 
code-time 4.1.15 
music-time 2.0.13 
node-debug 0.1.7 
script 3.26.0 
teletype 0.13.4 
```

**Comment by mmclead** [comment]
Thank you for reporting this.   we are working on a fix

**Comment by Laomoalosi** [comment]
There is also an Android Studio bug

**Comment by Laomoalosi** [comment]
It seems okay
